-- SUBSTATION

CREATE TABLE SABJI_CART.SUBSTATION (
	ID INT8 NOT NULL,
	SUBSTATION_NAME VARCHAR(40) NOT NULL,
	ACTIVE BOOLEAN DEFAULT FALSE,
	CREATED_BY VARCHAR(255) NOT NULL,
	MODIFIED_BY VARCHAR(255) NOT NULL,
	TIME_CREATED DECIMAL(20) NOT NULL,
	TIME_UPDATED DECIMAL(20) NOT NULL,
	VERSION DECIMAL(20) NOT NULL,
	PROPERTIES JSON,
	CONSTRAINT SUBSTATION_PKEY PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX SUBSTATION_NAME_IDX ON SABJI_CART.SUBSTATION (SUBSTATION_NAME);

-- CART

CREATE TABLE SABJI_CART.CART (
	ID INT8 NOT NULL,
	CART_PLATE_NUMBER VARCHAR(40) NOT NULL,
	ACTIVE BOOLEAN DEFAULT FALSE,
	CREATED_BY VARCHAR(255) NOT NULL,
	MODIFIED_BY VARCHAR(255) NOT NULL,
	TIME_CREATED DECIMAL(20) NOT NULL,
	TIME_UPDATED DECIMAL(20) NOT NULL,
	VERSION DECIMAL(20) NOT NULL,
	PROPERTIES JSON,
	CONSTRAINT CART_PKEY PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX CART_PLATE_NUMBER_IDX ON SABJI_CART.CART (CART_PLATE_NUMBER);

-- ITEM

CREATE TABLE SABJI_CART.ITEM (
	ID INT8 NOT NULL,
	ITEM_ID VARCHAR(40) NOT NULL,
	ITEM_NAME VARCHAR(40) NOT NULL,
	ITEM_DESCRIPTION VARCHAR(255),
	DENOMINATION VARCHAR(15) NOT NULL,
	ACTIVE BOOLEAN DEFAULT FALSE,
	CREATED_BY VARCHAR(255) NOT NULL,
	MODIFIED_BY VARCHAR(255) NOT NULL,
	TIME_CREATED DECIMAL(20) NOT NULL,
	TIME_UPDATED DECIMAL(20) NOT NULL,
	VERSION DECIMAL(20) NOT NULL,
	PROPERTIES JSON,
	CONSTRAINT ITEM_PKEY PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX ITEM_NAME_DENOMINATION_IDX ON SABJI_CART.ITEM (ITEM_NAME, DENOMINATION);
CREATE UNIQUE INDEX ITEM_ID_IDX ON SABJI_CART.ITEM (ITEM_ID);
