-- CART ITEMS

CREATE TABLE SABJI_CART.CART_ITEM (
	ID INT8 NOT NULL,
	CART_PLATE_NUMBER VARCHAR(40) NOT NULL,
	PROCESSING_DATE DATE NOT NULL,
	ITEM_ID VARCHAR(15) NOT NULL,
	QUANTITY_LOAD DECIMAL(10),
	QUANTITY_UNLOAD DECIMAL(10),
	QUANTITY_SALE DECIMAL(10),
	STATUS VARCHAR(15) NOT NULL,
	TIME_LOADED TIMESTAMP,
	TIME_UNLOADED TIMESTAMP,
	TIME_SALE_UPDATED TIMESTAMP,
	ACTIVE BOOLEAN DEFAULT FALSE,
	CREATED_BY VARCHAR(255) NOT NULL,
	MODIFIED_BY VARCHAR(255) NOT NULL,
	TIME_CREATED DECIMAL(20) NOT NULL,
	TIME_UPDATED DECIMAL(20) NOT NULL,
	VERSION DECIMAL(20) NOT NULL,
	PROPERTIES JSON,
	CONSTRAINT CART_ITEM_PKEY PRIMARY KEY (ID)
);

CREATE INDEX CART_PLATE_NUMBER_DATE_IDX ON SABJI_CART.CART_ITEM (CART_PLATE_NUMBER, PROCESSING_DATE);
CREATE UNIQUE INDEX CART_PLATE_NUMBER_DATE_ITEM_ID_IDX ON SABJI_CART.CART_ITEM (CART_PLATE_NUMBER, PROCESSING_DATE, ITEM_ID);
