CREATE TABLE SABJI_CART.SUBSTATION_CART (
   ID INT8 NOT NULL,
   SUBSTATION_ID INT8 NOT NULL,
   CART_ID INT8 NOT NULL,
   CART_PLATE_NUMBER VARCHAR(40) NOT NULL,
   CART_DRIVER_NAME VARCHAR(60) NOT NULL,
   ACTIVE BOOLEAN DEFAULT FALSE,
   CREATED_BY VARCHAR(255) NOT NULL,
   MODIFIED_BY VARCHAR(255) NOT NULL,
   TIME_CREATED DECIMAL(20) NOT NULL,
   TIME_UPDATED DECIMAL(20) NOT NULL,
   VERSION DECIMAL(20) NOT NULL,
   PROPERTIES JSON,
   CONSTRAINT SUBSTATION_CART_PKEY PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX SUBSTATION_CART_IDX ON SABJI_CART.SUBSTATION_CART (SUBSTATION_ID, CART_PLATE_NUMBER);