ALTER TABLE SABJI_CART.CART_ITEM
ADD COLUMN LOAD_STATUS VARCHAR(255)  DEFAULT 'TODO' NOT NULL,
ADD COLUMN UNLOAD_STATUS VARCHAR(255) DEFAULT 'TODO' NOT NULL,
ADD COLUMN SALE_STATUS VARCHAR(255) DEFAULT 'TODO' NOT NULL;
ALTER TABLE SABJI_CART.CART_ITEM DROP COLUMN STATUS;
