ALTER TABLE SABJI_CART.TRANSACTION_CATEGORY
    ADD COLUMN TRANSACTION_TYPE VARCHAR(255);

UPDATE SABJI_CART.TRANSACTION_CATEGORY
SET TRANSACTION_TYPE = 'DEBIT',
    CATEGORY_NAME='MISC-OT'
WHERE CATEGORY_NAME = 'MISC';

UPDATE SABJI_CART.TRANSACTION_CATEGORY
SET DESCRIPTION     = 'PROCUREMENT EXPENSE',
    TRANSACTION_TYPE='DEBIT'
WHERE CATEGORY_NAME = 'PROC';

UPDATE SABJI_CART.TRANSACTION_CATEGORY
SET TRANSACTION_TYPE='DEBIT'
WHERE CATEGORY_NAME = 'TF-OT';

UPDATE SABJI_CART.TRANSACTION_CATEGORY
SET TRANSACTION_TYPE='CREDIT'
WHERE CATEGORY_NAME = 'TF-IN';

UPDATE SABJI_CART.TRANSACTION_CATEGORY
SET TRANSACTION_TYPE='CREDIT'
WHERE CATEGORY_NAME = 'SCRD';

UPDATE SABJI_CART.TRANSACTION_CATEGORY
SET TRANSACTION_TYPE = 'CREDIT',
    CATEGORY_NAME='MISC-IN',
    DESCRIPTION='MISCELLANEOUS CREDIT'
WHERE CATEGORY_NAME = 'DEBT';
