CREATE TABLE SABJI_CART.ACCOUNT_TRANSACTION
(
    ID INT8 NOT NULL,
    AMOUNT DECIMAL(20) NOT NULL,
    REF_ID VARCHAR(255) NOT NULL,
    CREATOR VARCHAR(255) NOT NULL,
    COMMENT VARCHAR(255) NOT NULL,
    CURRENCY VARCHAR(255) NOT NULL,
    DATE DECIMAL(20) NOT NULL,
    TRANSACTION_TYPE VARCHAR(255) NOT NULL,
    ACTIVE BOOLEAN DEFAULT FALSE,
    CREATED_BY VARCHAR(255) NOT NULL,
    MODIFIED_BY VARCHAR(255) NOT NULL,
    TIME_CREATED DECIMAL(20) NOT NULL,
    TIME_UPDATED DECIMAL(20) NOT NULL,
    VERSION DECIMAL(20) NOT NULL,
    PROPERTIES JSON,
    CONSTRAINT ACCOUNT_TRANSACTION_PKEY PRIMARY KEY (ID)
);