CREATE TABLE SABJI_CART.BALANCE
(
    ID INT8 NOT NULL,
    AMOUNT DECIMAL(20) NOT NULL,
    DATE DECIMAL(20) NOT NULL,
    ACTIVE BOOLEAN DEFAULT FALSE,
    CREATED_BY VARCHAR(255) NOT NULL,
    MODIFIED_BY VARCHAR(255) NOT NULL,
    TIME_CREATED DECIMAL(20) NOT NULL,
    TIME_UPDATED DECIMAL(20) NOT NULL,
    VERSION DECIMAL(20) NOT NULL,
    PROPERTIES JSON,
    CONSTRAINT BALANCE_PKEY PRIMARY KEY (ID)
);