CREATE TABLE SABJI_CART.PROCUREMENT
(
    ID INT8 NOT NULL,
    ITEM_ID VARCHAR(10) NOT NULL,
    QUANTITY DECIMAL(10) NOT NULL,
    COST_PRICE DECIMAL(10) NOT NULL,
    UNIT_SELLING_PRICE DECIMAL(10),
    PROCUREMENT_DATE DECIMAL(20) NOT NULL,
    SUBSTATION_ID VARCHAR(10) NOT NULL,
    ACTIVE BOOLEAN DEFAULT FALSE,
    CREATED_BY VARCHAR(255) NOT NULL,
    MODIFIED_BY VARCHAR(255) NOT NULL,
    TIME_CREATED DECIMAL(20) NOT NULL,
    TIME_UPDATED DECIMAL(20) NOT NULL,
    VERSION DECIMAL(20) NOT NULL,
    CONSTRAINT PROCUREMENT_PKEY PRIMARY KEY (ID)
);