server:
  port: 8080
  servlet:
    context-path: /sabjicart

spring:
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration
    schemas: SABJI_CART
  mail:
    host: smtp.gmail.com
    port: 587
    username: amcec175@gmail.com
    password: Admin@175
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

  profiles:
    active: dev
jwt:
  secret: pysphere
address:
  url: https://api.getAddress.io/find/
  key: O-vbZ8Cu4EqwX9XPa_ERLw29608
mail:
  noreply: no-reply@sabjicart.com
springdoc:
  swagger-ui:
    path: /swagger/index.html
  api-docs:
    path: /swagger/api-docs

dekh-buy:
  health-check-url: http://localhost:8080/sabjicart/ping
